# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/fpga.xdc

# IP: ip/leverROM/leverROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==leverROM || ORIG_REF_NAME==leverROM} -quiet] -quiet

# IP: ip/quest_server/quest_server.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==quest_server || ORIG_REF_NAME==quest_server} -quiet] -quiet

# IP: ip/VRAM/VRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VRAM || ORIG_REF_NAME==VRAM} -quiet] -quiet

# IP: ip/res_picture/res_picture.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==res_picture || ORIG_REF_NAME==res_picture} -quiet] -quiet

# IP: ip/res_pic_index/res_pic_index.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==res_pic_index || ORIG_REF_NAME==res_pic_index} -quiet] -quiet
