# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/programm/verilog/game/core/core.runs/synth_1/GAME.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 5
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/programm/verilog/game/core/core.cache/wt [current_project]
set_property parent.project_path D:/programm/verilog/game/core/core.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/27643/AppData/Roaming/Xilinx/Vivado/2023.1/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.2 [current_project]
set_property ip_output_repo d:/programm/verilog/game/core/core.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files D:/programm/verilog/game/core/core.srcs/sources_1/ip/stateRAM/stateRAM_tb.coe
add_files D:/programm/verilog/game/core/core.srcs/sources_1/ip/leverROM.coe
add_files D:/programm/verilog/game/core/core.srcs/sources_1/ip/res_picture/res_picture.coe
add_files D:/programm/verilog/game/core/core.srcs/sources_1/ip/res_pic_index/res_index.coe
add_files D:/programm/verilog/game/core/core.srcs/sources_1/ip/quest_server/quest_server.coe
add_files D:/programm/verilog/game/core/core.srcs/sources_1/ip/VRAM/VRAM.coe
add_files D:/programm/verilog/game/core/core.srcs/sources_1/ip/mROM.coe
read_verilog -library xil_defaultlib -sv {
  D:/programm/verilog/game/core/core.srcs/sources_1/new/DCD.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/DDP.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/DST.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/DU.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/SP.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/add_block.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/change_block.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/clock.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/core.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/ctrl.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/decode.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/game_end.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/game_run.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/game_run_background.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/game_run_block.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/game_run_key_error.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/game_run_player.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/game_start.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/game_wait.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/key.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/music.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/player.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/ps2_transmitter.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/request.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/reset_state.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/score.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/send_request.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/state_str.sv
  D:/programm/verilog/game/core/core.srcs/sources_1/new/GAME.sv
}
read_ip -quiet D:/programm/verilog/game/core/core.srcs/sources_1/ip/leverROM/leverROM.xci
set_property used_in_implementation false [get_files -all d:/programm/verilog/game/core/core.gen/sources_1/ip/leverROM/leverROM_ooc.xdc]

read_ip -quiet D:/programm/verilog/game/core/core.srcs/sources_1/ip/quest_server/quest_server.xci
set_property used_in_implementation false [get_files -all d:/programm/verilog/game/core/core.gen/sources_1/ip/quest_server/quest_server_ooc.xdc]

read_ip -quiet D:/programm/verilog/game/core/core.srcs/sources_1/ip/VRAM/VRAM.xci
set_property used_in_implementation false [get_files -all d:/programm/verilog/game/core/core.gen/sources_1/ip/VRAM/VRAM_ooc.xdc]

read_ip -quiet D:/programm/verilog/game/core/core.srcs/sources_1/ip/res_picture/res_picture.xci
set_property used_in_implementation false [get_files -all d:/programm/verilog/game/core/core.gen/sources_1/ip/res_picture/res_picture_ooc.xdc]

read_ip -quiet D:/programm/verilog/game/core/core.srcs/sources_1/ip/res_pic_index/res_pic_index.xci
set_property used_in_implementation false [get_files -all d:/programm/verilog/game/core/core.gen/sources_1/ip/res_pic_index/res_pic_index_ooc.xdc]

read_ip -quiet D:/programm/verilog/game/core/core.srcs/sources_1/ip/bclk/bclk.xci
set_property used_in_implementation false [get_files -all d:/programm/verilog/game/core/core.srcs/sources_1/ip/bclk/bclk_board.xdc]
set_property used_in_implementation false [get_files -all d:/programm/verilog/game/core/core.srcs/sources_1/ip/bclk/bclk.xdc]
set_property used_in_implementation false [get_files -all d:/programm/verilog/game/core/core.srcs/sources_1/ip/bclk/bclk_ooc.xdc]

read_ip -quiet D:/programm/verilog/game/core/core.srcs/sources_1/ip/stateRAM/stateRAM.xci
set_property used_in_implementation false [get_files -all d:/programm/verilog/game/core/core.gen/sources_1/ip/stateRAM/stateRAM_ooc.xdc]

read_ip -quiet D:/programm/verilog/game/core/core.srcs/sources_1/ip/mROM/mROM.xci
set_property used_in_implementation false [get_files -all d:/programm/verilog/game/core/core.srcs/sources_1/ip/mROM/mROM_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/programm/verilog/game/core/core.srcs/constrs_1/new/fpga.xdc
set_property used_in_implementation false [get_files D:/programm/verilog/game/core/core.srcs/constrs_1/new/fpga.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/programm/verilog/game/core/core.srcs/utils_1/imports/synth_1/TOP_test.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top GAME -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef GAME.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file GAME_utilization_synth.rpt -pb GAME_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
