# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/programm/verilog/game/core/core.srcs/sources_1/ip/stateRAM/stateRAM.xci
# IP: The module: 'stateRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/programm/verilog/game/core/core.gen/sources_1/ip/stateRAM/stateRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'stateRAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/programm/verilog/game/core/core.srcs/sources_1/ip/stateRAM/stateRAM.xci
# IP: The module: 'stateRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/programm/verilog/game/core/core.gen/sources_1/ip/stateRAM/stateRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'stateRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
