# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/programm/verilog/game/core/core.srcs/sources_1/ip/bclk/bclk.xci
# IP: The module: 'bclk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/programm/verilog/game/core/core.srcs/sources_1/ip/bclk/bclk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bclk'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/programm/verilog/game/core/core.srcs/sources_1/ip/bclk/bclk.xdc
# XDC: The top module name and the constraint reference have the same name: 'bclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/programm/verilog/game/core/core.srcs/sources_1/ip/bclk/bclk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/programm/verilog/game/core/core.srcs/sources_1/ip/bclk/bclk.xci
# IP: The module: 'bclk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/programm/verilog/game/core/core.srcs/sources_1/ip/bclk/bclk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/programm/verilog/game/core/core.srcs/sources_1/ip/bclk/bclk.xdc
# XDC: The top module name and the constraint reference have the same name: 'bclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/programm/verilog/game/core/core.srcs/sources_1/ip/bclk/bclk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
